# Generated by Django 3.0.3 on 2020-02-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGuid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='دسته بندی راهنمایی ها')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='دسته بندی')),
                ('about', models.TextField()),
                ('address', models.FilePathField(path='File/Guid')),
                ('categoryguid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.CategoryGuid')),
            ],
        ),
    ]
