# Generated by Django 3.0.3 on 2020-02-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guild',
            new_name='Guid',
        ),
    ]
