# Generated by Django 3.0.3 on 2020-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200215_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guid',
            name='address',
            field=models.FileField(upload_to='FileGuid/'),
        ),
    ]
