# Generated by Django 3.0.3 on 2020-02-12 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200212_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='address',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/post/'),
            preserve_default=False,
        ),
    ]
