# Generated by Django 3.0.3 on 2020-02-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200213_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='defaultImage',
            field=models.ImageField(blank=True, null=True, upload_to='img/News', verbose_name='عکس پیش فرض'),
        ),
    ]
